---
name: Build container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - files/**
      - scripts/*
  pull_request:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - files/**
      - scripts/*

jobs:
  build-container-image:
    strategy:
      matrix:
        version:
          - 1.5.7
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build container image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          VERSION: ${{ matrix.version }}
          REPOSITORY: osism/ara-server

      - name: Push container image
        run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          VERSION: ${{ matrix.version }}
          REPOSITORY: osism/ara-server
        if: github.ref == 'refs/heads/main'
